import 'package:flutter/widgets.dart';

class AppStrings {
  AppStrings(this.code);
  final String code;
  static const supportedLocales = [Locale('en'), Locale('ur'), Locale('ar')];
  static const _values = <String, Map<String, String>>{
    'en': {
      'appName': 'Azan Academy',
      'subtitle': 'Listen. Repeat. Improve.',
      'learn': 'Learn Azan',
      'progress': 'My Progress',
      'settings': 'Settings',
      'search': 'Search Azans',
      'azanGuide': 'Azan guide',
      'whatIsAzan': 'What is Azan?',
      'whatIsAzanBody':
          'Azan is the Islamic call to prayer, announced five times a day to invite Muslims toward worship with clarity, respect, and devotion.',
      'benefitsOfAzan': 'Fazilat of Azan',
      'benefitsOfAzanBody':
          'Hadith mentions great reward in giving the Azan and standing in the first row (Sahih al-Bukhari 615). Whoever hears the Muazzin will testify for him on the Day of Resurrection (Sahih al-Bukhari 609), and the Muazzins will have a special honor on that Day (Sahih Muslim 387).',
      'all': 'All',
      'favorites': 'Favorites',
      'about': 'About this style',
      'listen': 'Listen to Azan',
      'reciter': 'Reciter',
      'muazzinDetails': 'Muazzin Details',
      'mosque': 'Mosque',
      'location': 'Location',
      'placeInfo': 'Place and image',
      'selectAudio': 'Select audio',
      'downloadOnFirstPlay':
          'The complete pack downloads automatically the first time you listen.',
      'downloading': 'Downloading Azan pack…',
      'downloaded': 'Downloaded • available offline',
      'tapToDownload': 'Tap to download and listen',
      'downloadAudio': 'Download audio',
      'downloadFirst': 'Download this audio before playing it.',
      'downloadFailed': 'Unable to download this Azan pack.',
      'takbeerOnly': 'Takbeer only',
      'callOnly': "Hayya 'alas-Salah call",
      'fullAzan': 'Full Azan',
      'fajrAzan': 'Fajr Azan',
      'practice': 'Start practice',
      'audioPending': 'Authentic audio coming soon',
      'phrase': 'Phrase',
      'of': 'of',
      'reference': 'Reference',
      'record': 'Tap to record',
      'recording': 'Recording…',
      'stop': 'Stop recording',
      'playMine': 'Play my recording',
      'pauseMine': 'Pause my recording',
      'next': 'Next phrase',
      'finish': 'Finish',
      'complete': 'Practice complete',
      'wellDone': 'Well done. Consistent practice builds confidence.',
      'done': 'Done',
      'practiceAgain': 'Practice again',
      'language': 'Language',
      'appearance': 'Appearance',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'empty': 'No Azans match this selection.',
      'demoNotice':
          'Demo catalogue • Verified audio will be added before release',
      'permission':
          'Microphone permission is required to record your practice.',
      'attempts': 'Practice attempts',
      'completed': 'Completed sessions',
      'myRecordings': 'My recordings',
      'noRecordings': 'No recordings yet. Practice any Azan to see it here.',
      'recordedFor': 'Recorded for',
      'missingRecording': 'Recording file is not available on this device.',
      'shareRecording': 'Share recording',
    },
    'ur': {
      'appName': 'اذان اکیڈمی',
      'subtitle': 'سنیں، دہرائیں، بہتر بنائیں',
      'learn': 'اذان سیکھیں',
      'progress': 'میری پیش رفت',
      'settings': 'ترتیبات',
      'search': 'اذان تلاش کریں',
      'azanGuide': 'اذان گائیڈ',
      'whatIsAzan': 'اذان کیا ہے؟',
      'whatIsAzanBody':
          'اذان نماز کی اسلامی دعوت ہے جو دن میں پانچ مرتبہ دی جاتی ہے تاکہ مسلمان ادب، وضاحت اور اخلاص کے ساتھ عبادت کی طرف آئیں۔',
      'benefitsOfAzan': 'اذان کی فضیلت',
      'benefitsOfAzanBody':
          'حدیث میں اذان دینے اور پہلی صف میں کھڑے ہونے کی بڑی فضیلت بیان ہوئی ہے (صحیح البخاری 615)۔ مؤذن کی آواز جو بھی سنے گا وہ قیامت کے دن اس کے حق میں گواہی دے گا (صحیح البخاری 609)، اور مؤذنوں کے لیے قیامت کے دن خاص اعزاز ہوگا (صحیح مسلم 387)۔',
      'all': 'تمام',
      'favorites': 'پسندیدہ',
      'about': 'اس انداز کے بارے میں',
      'listen': 'اذان سنیں',
      'reciter': 'قاری',
      'muazzinDetails': 'مؤذن کی تفصیلات',
      'mosque': 'مسجد',
      'location': 'مقام',
      'placeInfo': 'مقام اور تصویر',
      'selectAudio': 'آڈیو منتخب کریں',
      'downloadOnFirstPlay':
          'پہلی بار سننے پر مکمل پیک خودکار طور پر ڈاؤن لوڈ ہوگا۔',
      'downloading': 'اذان پیک ڈاؤن لوڈ ہو رہا ہے…',
      'downloaded': 'ڈاؤن لوڈ شدہ • آف لائن دستیاب',
      'tapToDownload': 'ڈاؤن لوڈ اور سننے کے لیے دبائیں',
      'downloadAudio': 'آڈیو ڈاؤن لوڈ کریں',
      'downloadFirst': 'سننے سے پہلے یہ آڈیو ڈاؤن لوڈ کریں۔',
      'downloadFailed': 'یہ اذان پیک ڈاؤن لوڈ نہیں ہو سکا۔',
      'takbeerOnly': 'صرف تکبیر',
      'callOnly': 'حی علی الصلاۃ کی صدا',
      'fullAzan': 'مکمل اذان',
      'fajrAzan': 'فجر کی اذان',
      'practice': 'مشق شروع کریں',
      'audioPending': 'مستند آڈیو جلد شامل ہوگی',
      'phrase': 'جملہ',
      'of': 'از',
      'reference': 'حوالہ آڈیو',
      'record': 'ریکارڈ کرنے کے لیے دبائیں',
      'recording': 'ریکارڈنگ جاری ہے…',
      'stop': 'ریکارڈنگ روکیں',
      'playMine': 'میری ریکارڈنگ سنیں',
      'pauseMine': 'میری ریکارڈنگ روکیں',
      'next': 'اگلا جملہ',
      'finish': 'مکمل کریں',
      'complete': 'مشق مکمل ہوگئی',
      'wellDone': 'بہت خوب۔ مسلسل مشق اعتماد پیدا کرتی ہے۔',
      'done': 'ہو گیا',
      'practiceAgain': 'دوبارہ مشق کریں',
      'language': 'زبان',
      'appearance': 'ظاہری شکل',
      'system': 'سسٹم',
      'light': 'روشن',
      'dark': 'تاریک',
      'empty': 'اس انتخاب میں کوئی اذان نہیں ملی۔',
      'demoNotice': 'نمونہ فہرست • مستند آڈیو ریلیز سے پہلے شامل ہوگی',
      'permission': 'مشق ریکارڈ کرنے کے لیے مائیکروفون کی اجازت ضروری ہے۔',
      'attempts': 'مشق کی کوششیں',
      'completed': 'مکمل سیشن',
      'myRecordings': 'میری ریکارڈنگز',
      'noRecordings': 'ابھی کوئی ریکارڈنگ نہیں۔ کسی اذان کی مشق کریں۔',
      'recordedFor': 'ریکارڈنگ برائے',
      'missingRecording': 'یہ ریکارڈنگ اس ڈیوائس پر دستیاب نہیں۔',
      'shareRecording': 'ریکارڈنگ شیئر کریں',
    },
    'ar': {
      'appName': 'أكاديمية الأذان',
      'subtitle': 'استمع، كرّر، وتقدّم',
      'learn': 'تعلّم الأذان',
      'progress': 'تقدّمي',
      'settings': 'الإعدادات',
      'search': 'ابحث عن أذان',
      'azanGuide': 'دليل الأذان',
      'whatIsAzan': 'ما هو الأذان؟',
      'whatIsAzanBody':
          'الأذان هو النداء الإسلامي للصلاة، يرفع خمس مرات يوميًا لدعوة المسلمين إلى العبادة بوضوح وخشوع.',
      'benefitsOfAzan': 'فضل الأذان',
      'benefitsOfAzanBody':
          'ورد في الحديث فضل عظيم للأذان والصف الأول (صحيح البخاري 615). وكل من يسمع صوت المؤذن يشهد له يوم القيامة (صحيح البخاري 609)، وللمؤذنين كرامة خاصة يوم القيامة (صحيح مسلم 387).',
      'all': 'الكل',
      'favorites': 'المفضلة',
      'about': 'عن هذا الأسلوب',
      'listen': 'استمع إلى الأذان',
      'reciter': 'المؤذن',
      'muazzinDetails': 'تفاصيل المؤذن',
      'mosque': 'المسجد',
      'location': 'الموقع',
      'placeInfo': 'المكان والصورة',
      'selectAudio': 'اختر التسجيل',
      'downloadOnFirstPlay':
          'يتم تنزيل الحزمة كاملة تلقائيًا عند الاستماع لأول مرة.',
      'downloading': 'جارٍ تنزيل حزمة الأذان…',
      'downloaded': 'تم التنزيل • متاح دون اتصال',
      'tapToDownload': 'اضغط للتنزيل والاستماع',
      'downloadAudio': 'تنزيل الصوت',
      'downloadFirst': 'نزّل هذا الصوت قبل تشغيله.',
      'downloadFailed': 'تعذر تنزيل حزمة الأذان.',
      'takbeerOnly': 'التكبير فقط',
      'callOnly': 'نداء حي على الصلاة',
      'fullAzan': 'الأذان الكامل',
      'fajrAzan': 'أذان الفجر',
      'practice': 'ابدأ التدريب',
      'audioPending': 'سيتم إضافة الصوت الموثّق قريبًا',
      'phrase': 'العبارة',
      'of': 'من',
      'reference': 'الصوت المرجعي',
      'record': 'اضغط للتسجيل',
      'recording': 'جارٍ التسجيل…',
      'stop': 'إيقاف التسجيل',
      'playMine': 'تشغيل تسجيلي',
      'pauseMine': 'إيقاف تسجيلي مؤقتًا',
      'next': 'العبارة التالية',
      'finish': 'إنهاء',
      'complete': 'اكتمل التدريب',
      'wellDone': 'أحسنت. الممارسة المستمرة تبني الثقة.',
      'done': 'تم',
      'practiceAgain': 'تدرّب مرة أخرى',
      'language': 'اللغة',
      'appearance': 'المظهر',
      'system': 'النظام',
      'light': 'فاتح',
      'dark': 'داكن',
      'empty': 'لا توجد نتائج لهذا الاختيار.',
      'demoNotice': 'محتوى تجريبي • سيضاف الصوت الموثّق قبل الإصدار',
      'permission': 'يلزم السماح باستخدام الميكروفون لتسجيل التدريب.',
      'attempts': 'محاولات التدريب',
      'completed': 'الجلسات المكتملة',
      'myRecordings': 'تسجيلاتي',
      'noRecordings': 'لا توجد تسجيلات بعد. تدرّب على أي أذان لتظهر هنا.',
      'recordedFor': 'تسجيل لـ',
      'missingRecording': 'ملف التسجيل غير متاح على هذا الجهاز.',
      'shareRecording': 'مشاركة التسجيل',
    },
  };
  String t(String key) => _values[code]?[key] ?? _values['en']![key] ?? key;
  bool get isRtl => code == 'ur' || code == 'ar';
}
